name: Syncify-CI

on:
    push:
        branches: [master, development]
    pull_request:
        branches: [master, development]

jobs:
    build:
        name: Test
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up Node
              run: |
                  npm install -g react-native-cli
                  npm install -g detox-cli
                  npm install -g yarn
              #run: |
              #brew tap wix/brew
              #brew install applesimutils
            #- name: Install Detox
            - name: Install Yarn Dependencies
              run: yarn install
            - name: Lint
              run: yarn lint
            # - name: Install Pod Dependencies
            #  run: cd ./ios && pod install && cd ..
            # - name: Detox Build
            #   run: detox build -c ios.release
            # - name: Detox Test
            #run: detox test -c ios.release
